### ISSUE TITLE
Preprint venue

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#12]
Let's use this issue to vote on the preprint venue, one platform per comment.
Goal is to publish the preprint _end of October 2019_.
The platform should support posting the PDF as it is generated now.

Use as many :+1: and :-1: as you like (maybe adding a comment why in the case of the latter) so we can also do a negative sorting (choose the one where least people have valid concerns).

**Comment by nuest** [comment]
~~PeerJ~~ ([closing down end of Sep](https://peerj.com/blog/post/115284881747/peerj-preprints-to-stop-accepting-new-preprints-sep-30-2019/))

**Comment by nuest** [comment]
[Preprints.org](https://www.preprints.org/)

Run by MDPI, https://www.preprints.org/about, have comments, indexed well.

**Comment by nuest** [comment]
[arXiv](https://arxiv.org/)

THE preprint server, but no DOI.

**Comment by nuest** [comment]
[OSF preprints](https://osf.io/preprints/)

Open platform, non-profit.

**Comment by nuest** [comment]
[Zenodo](https://zenodo.org/)

Not known as preprint server that much, more code/data/supplemental material.

**Comment by nanxstats** [comment]
MDPI is mostly a [predatory publisher](https://en.wikipedia.org/wiki/MDPI) so probably no... 😂

**Comment by nuest** [comment]
Winner: arXiv

![image](https://user-images.githubusercontent.com/1325054/70902225-99c0f200-1ffc-11ea-93a1-8a6b66c77a66.png)
