### ISSUE TITLE
card.com Dockerfiles - check them out

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#15]
https://github.com/cardcorp/card-rocker

**Comment by nuest** [comment]
Hi @daroczig :wave: ! It seems you have done some work on R and containers :-) Would you be interested in checking out the current draft and topics at https://github.com/nuest/rockerverse-paper/blob/master/manuscript.Rmd? We're still open for new ideas and contributions, if there is a topic that you'd like to share from your work/research around/based on the "Rockerverse". And any kind of feedback of course!

**Comment by nuest** [comment]
Please feel free to re-open.

**Comment by daroczig** [comment]
Sorry for the long delay -- just opened #62 62
