### ISSUE TITLE
rockerverse package

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#2]
just like https://cran.r-project.org/package=tidyverse

IMO this could be quite helpful (though unlikely to get to CRAN?) because it could manage the installation sources, i.e. install some packages from CRAN while others from GitHub.

```R
library("rockerverse")
#> ── Attaching packages ────────────────────────────── rockerverse 1.0.0 ──
#> ✔ stevedore 1.2.3 (CRAN)
#> ✔ doker 1.2.3 (CRAN)
#> ✔ dockerfiler 1.1.1 (CRAN)
#> ✔ containerit 2.2.2 (GitHub)

rockerverse::install_deprecated()
# install harbour, dockermachine, ...
```

**Comment by nuest** [comment]
Could the package also run a few tests to make sure that Docker is installed and available, before installing all the tools that rely on it?

**Comment by rcannood** [comment]
At babelwhale we have a few tests for [Docker](https://github.com/dynverse/babelwhale/blob/master/R/test_docker_installation.R) and [Singularity](https://github.com/dynverse/babelwhale/blob/master/R/test_singularity_installation.R), though these might certainly need to be extended further.

**Comment by nuest** [comment]
@rcannood The tests look quite extensive to me - what else would you think should be checked?

**Comment by nuest** [comment]
- [ ] If we have a package, it needs a hex sticker, obviously.

**Comment by nuest** [comment]
Just came across this one, and it seems to be a great boilerplate: https://github.com/mlr-org/mlr3verse (though it does not need packages from GitHub)

**Comment by eddelbuettel** [comment]
Allow me to play devil's advocate:

- the (so-called) "rockerverse" collection appears to be a suite of mostly unrelated, non-overlapping packages
- so even installing one or two may not influence the likelihood of needing or wanting the remaining ones
- so why force them?
- mlr3 is actually a set of packages working together so having a bundle makes sense
- whereas this is more like a loosely unrelated collection, like my four RMarkdown wrapping packages which have a non-verse collector (not on CRAN !!) mostly as a joke: https://github.com/eddelbuettel/minm

**Comment by nuest** [comment]
You convinced me! The hex sticker is still worth wasting some time on :-) 

![image](https://user-images.githubusercontent.com/1325054/72073313-f65bb800-32ef-11ea-90fc-247b0986fe94.png)
