### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#26]
IMO the [R Journal](https://journal.r-project.org) is the most fitting venue for this article, so (unlike the [preprint server](#12)) I decided _not_ to start a vote. Please raise your concerns here. We can also reach out to the [editors](https://journal.r-project.org/board.html) pre-submission.

## Missing pieces

There are a few ideas for small additions to the article, see https://github.com/nuest/rockerverse-paper/issues?q=is%3Aissue+is%3Aopen+label%3A%22after+preprint%22

## Concerns

The article is by now quite long! #65 already removed substantial content, but the references and author list together are also 6 pages. 

## Timing

Preprint went out end of January 2020 #27.

I think it would be great to invite the broader community to give feedback during February, then prepare a version for **submission beginning of March 2020**.

## Final checklist

- [x] Double check submission guide: https://journal.r-project.org/share/author-guide.pdf
- [x] Request all coauthors to fill out the template below in a comment to this issue
- [x] [All coauthors confirmed](https://github.com/nuest/rockerverse-paper/issues/26#issuecomment-593365256)
- [x] Fill out R Journal Checklist (below)
- [ ] update preprint
- [x] Create a tag for the submission version

## Template for contributors

```
- [ ] I approve the final version
- [ ] I have checked my affiliation information
- [ ] I have checked the contribution statement and it adequately describes what I did
- [ ] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [ ] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)
```

**NB: @nuest acknowledges this might seem tedious, but a "does anybody object" vote does not do the importance of this step justice.**

## _R Journal_ checklist

- [x] I have read the instructions for authors, and include a motivating letter if my submission is of the "add-on packages" type
- [x] I am using the latest version of the style file
- [x] My bibliography is stored in a separate bibtex (filename.bib) file
- [x] My article is called filename.tex, my graphics files are PDF and/or PNG, my reproduction script is called filename.R, and I have updated RJwrapper.tex
- [x] I acknowledge that if accepted my article will be published with CC-BY license
- [x] The manuscript has not been published in a peer reviewed journal, and is not currently under review for another journal
- [x] All authors agree to submission of the article to the R Journal
- _Article length_ :The R Journal has no page limit. However, there is a tendency for longer papers to besubject to longer reviewing time, and excessive length may reduce your article’s readership, should it be published. If possible, try to limit your article’s length to, say, 8-10 pages, excluding figures and bibliography.
  - **We are currently at a little over 15 pages, 24 in total.**

## Submission preparation

- ~~If the submission is of the “add-on packages” type, a motivating letter (PDF or plain text,please) explaining how you meet our requirements described above (2.1).~~
- [ ] The modified ‘RJwrapper.tex’ 
- [ ] ‘RJwrapper.pdf’
- [ ] ‘rockerverse.tex’
- [ ] ‘RJreferences.bib’
- [ ] all necessary figure files (only PDF or PNG files are accepted): `figures/*`
- [ ] an R script (‘rockerverse.RR’ using the same file name as that created above) permitting the reproduction of examples in your submission and small data files — use built-in data setswhere sensible, see below.
- [ ] Do not include ‘RJournal.sty’ or style files for other latex packages needed by your article.
- [ ] You should have only one ‘.bib’ file, and only two ‘.tex’ files, one of which is ‘RJwrapper.tex’.

**Comment by daroczig** [comment]
Thanks again for your hard work on this, really excited about seeing this in the R Journal!

- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by nuest** [comment]
@eddelbuettel
@DomBennett
@rcannood
@davclark
@ColinFay
@thebioengineer
@smaakage85
@slopp
@benmarwick/
@nolistic/
@jnolis/
@Hong-Revo
@karthik
@noamross
@lshep
@psolymos
@tyson-swetnam
@nturaga
@jasonjwilliamsny
@craig-willis
@nanxstats
@charvp

**Comment by nuest** [comment]
@daroczig content has changed, please re-check your first box. Thanks! (Also: don't you want the ó in your last name?)

**Comment by nuest** [comment]
@nuest @eddelbuettel @DomBennett @rcannood @davclark @ColinFay @thebioengineer @smaakage85 @slopp @benmarwick @nolistic @jnolis @Hong-Revo @karthik @noamross @lshep @psolymos @tyson-swetnam @nturaga @jasonjwilliamsny @craig-willis @nanxstats @charvp Please fill in [the template](https://github.com/nuest/rockerverse-paper/issues/26#issue-518356119). Thanks!

**Comment by charvp** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [ ] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

I created #75 to add my contribution to the contribution statement.

**Comment by benmarwick** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by psolymos** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by lshep** [comment]
- [X] I approve the final version
- [X] I have checked my affiliation information
- [X] I have checked the contribution statement and it adequately describes what I did
- [X] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [X] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

Please see [#76](https://github.com/nuest/rockerverse-paper/pull/76) for Acknowledgements section to include funding information for myself and @nturaga

**Comment by JasonJWilliamsNY** [comment]
- [ ] I approve the final version
- [ ] I have checked my affiliation information
- [ ] I have checked the contribution statement and it adequately describes what I did
- [ ] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [ ] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

@tyson-swetnam - I added our contributions in #77

**Comment by nanxstats** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by karthik** [comment]
- [ ] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [ ] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by karthik** [comment]
I'll check off the acknowledgement after you merge my latest PR.

**Comment by eddelbuettel** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

I have a screenful of small typos (and one or two medium-sized issues) that I will email you as I fear that too many parallel PRs may wreak havoc on the document.

That said:  Thanks so much starting and leading this, and herding all us cats!   :cake:

**Comment by ColinFay** [comment]
- [X] I approve the final version
- [X] I have checked my affiliation information
- [X] I have checked the contribution statement and it adequately describes what I did
- [X] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [X] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

Thanks for putting that into motion Daniel, amazing work!

**Comment by tyson-swetnam** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

Thanks for the opportunity to contribute, honored to be a part of this group.

**Comment by craig-willis** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

I've suggested two super minor changes https://github.com/nuest/rockerverse-paper/pull/80.

Thanks again for organizing this and for the opportunity to participate!

**Comment by Hong-Revo** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

This looks awesome. Really looking forward to seeing this in the Journal. 👍

**Comment by smaakage85** [comment]
* [X] I approve the final version
* [x]  I have checked my affiliation information
* [x]  I have checked the contribution statement and it adequately describes what I did
* [x]  I have checked the "Acknowledgements" to include the funding that supports my contribution.
* [x]  I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

very good job!! :)

**Comment by jnolis** [comment]
- [X] I approve the final version
- [X] I have checked my affiliation information
- [X] I have checked the contribution statement and it adequately describes what I did
- [X] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [X] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by noamross** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information (pending #83)
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by MarkEdmondson1234** [comment]
- [ x] I approve the final version
- [x ] I have checked my affiliation information
- [x ] I have checked the contribution statement and it adequately describes what I did
- [x ] I have checked the "Acknowledgements" to include the funding that supports my contribution. (I have no funding so left it blank?)
- [ x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by nuest** [comment]
Thanks to everyone who replied so far - this is progressing at a decent pace. I've just sent a friendly reminder to the remaining contributors.

**@ all:** Note we had some small additions, spelling error corrections, and format adjustments since the first call for approvals. I do _not_ think these warrant a reevaluation by the people providing their approval in the meantime. If you disagree, please let us know.

Always find the current draft here: https://nuest.github.io/rockerverse-paper/master.pdf

The changes since the first call for approvals: https://github.com/nuest/rockerverse-paper/compare/preprint.v2...master#diff-b031376ea6cb8ca666ceb2938a60be15

**Comment by davclark** [comment]
- [ ] I approve the final version
- [ ] I have checked my affiliation information
- [ ] I have checked the contribution statement and it adequately describes what I did
- [ ] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [ ] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by rcannood** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by DomBennett** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [x] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by slopp** [comment]
- [ ] I approve the final version
- [ ] I have checked my affiliation information
- [ ] I have checked the contribution statement and it adequately describes what I did
- [ ] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [ ] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

**Comment by thebioengineer** [comment]
- [x] I approve the final version
- [x] I have checked my affiliation information
- [ ] I have checked the contribution statement and it adequately describes what I did
- [x] I have checked the "Acknowledgements" to include the funding that supports my contribution.
- [x] I agree to submit the article to the R Journal (where it will be reviewed and if accepted published with CC-BY license)

In the contribution statement, it calls out _dynverse_ and `dynwrap`, which I did not contribute to. Not sure if that should be moved? Otherwise I am in agreement!

**Comment by nuest** [comment]
@thebioengineer Please check if this update works for you: https://github.com/nuest/rockerverse-paper/commit/eb528a2711a4f4ec84b71238abe55ed7bdd46d13

**Comment by thebioengineer** [comment]
Looks good @nuest - thanks for making the edit!

**Comment by nuest** [comment]
![image](https://user-images.githubusercontent.com/1325054/76620645-ed74a600-652d-11ea-8fbd-88c2f9de2c19.png)

https://github.com/nuest/rockerverse-paper/tree/submission

**Comment by nuest** [comment]
Hi @eddelbuettel @DomBennett @rcannood @davclark @daroczig @MarkEdmondson1234 @ColinFay @thebioengineer @smaakage85 @slopp @benmarwick @nolistic @jnolis @Hong-Revo @karthik @noamross @lshep @psolymos @tyson-swetnam @nturaga @charvp @jasonjwilliamsny @craig-willis @nanxstats !

_I just received news from The R Journal that our submission is accepted!_

I asked how to proceed with the small updates we had in the meantime (#90), will keep you in the loop.

Thanks to all of you for making this a fun and educating collaboration. I hope this repo remains useful after the paper is out, and I'd be happy to publish updates of the preprint when there are major updates to the Rockerverse, and then there's the idea of a Containerisation Task View... #47. But today, I'm happy about a small bit of good news that made my day. I hope you can enjoy this, too, and that you're all healthy and safe!
