### ISSUE TITLE
Submit preprint mid-January

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#27]
Submit a first version of the article to arXiv (see #12 for voting on the venue).
If we manage to get a first complete version out by end of the year, we can seek feedback/advertise during [rstudio::conf (end of January)](https://rstudio.com/conference/).

## Archive and Subject Class

I suggest `cs.SE` (computer science - software engineering) as the category, see [arXiv Category Taxonomy](https://arxiv.org/category_taxonomy). Alternatives could be "Other Computer Science" (`os.OH`). The 

## License

CC BY 4.0 (matching the R Journal's license, #26)

-------

**Any objections against subject class or license?** Please raise them here.

**Comment by nuest** [comment]
Next steps here:

- post first preprint-ready draft here end of year 2019
- have a "voting" comment for all then listed co-authors to approve the draft (incl. affiliations, contribution section, general content) with a mid-January deadline
- submit to arXiv #12 and hope it's ready in time for all rstudio::conf-goers to read it on their trip there :smirk:

**Comment by eddelbuettel** [comment]
It's all good and I am game.  I am fail confused about what RStudio::conf has to do with anything.  We are writing the paper virtually so all deadlines are ours.  (I think you are just being sneaky waving a commonly understood deadline device here....)

**Comment by nuest** [comment]
Not trying to be sneaky :smile: I think a few of the co-authors (not me) might be going there (?), and the R community will be actively chatting about what's hot/new, and we could use that event to also get the preprint noticed.

**Comment by nuest** [comment]
Currently working on getting an endorsement for `cs.SE`. Help appreciated!

**Comment by nuest** [comment]
Got the endorsement, article is submitted.

**Comment by nuest** [comment]
![image](https://user-images.githubusercontent.com/1325054/73260901-3f09e100-41cb-11ea-9a56-bb5759c15242.png)

![image](https://user-images.githubusercontent.com/1325054/73260911-47621c00-41cb-11ea-87e0-3ba427d4893b.png)

**Comment by eddelbuettel** [comment]
Minor issue (that gets me frequently too) is the left-over `~` from LaTeX spacing. I would suggest `s/Rocker~Project/Rocker Project/`.

Congratulations, otherwise :)

**Comment by nuest** [comment]
Verflixt!

**Comment by nuest** [comment]
I made an update, because two footnotes were also brokwn. The article was "on hold" anyway... probably will not be out quickly.

**Comment by nuest** [comment]
https://arxiv.org/abs/2001.10641

![image](https://user-images.githubusercontent.com/1325054/73431996-06404800-4342-11ea-87a6-ae4c8235f929.png)
