### ISSUE TITLE
Mention Gigantum image stack

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#29]
Gigantum uses it's own image stack, which includes two R-related images: https://github.com/gigantum/base-images

Currently there is no contributor who would like to describe this.

**Comment by nuest** [comment]
Reason for an independent stack seemed to be licensing issues: https://twitter.com/davclark/status/1151267145398902784

@davclark Hi there! Is the comment in the issue above the whole story, or would you be interested in contributing a short paragraph about the Gigantum image stack to this overview article?

**Comment by davclark** [comment]
Just got the email from @nuest and responded there... but I'll try to pay closer attention in this issue as well!
