### ISSUE TITLE
Rockerverse paper collaboration

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#3]
The R Journal article about Rocker, https://journal.r-project.org/archive/2017/RJ-2017-065/index.html, is a great introduction, but by now there is almost an ecosystem of packages around the Rocker project.

Looking at [a recent tweet](https://twitter.com/noamross/status/1151254374771019777) reminded me of this idea for a paper capturing the full breadth of Docker/containers in R; demonstrating all the different usages of Rocker images and related R packages for working with Docker, Dockerfiles, etc., and then trying to coin the term _Rockerverse_.

_The idea is stuck at "I think this is a worth writing about"_, and probably won't get anywhere without **collaborators** to go back and forth a bit. I imagine everyone can contribute a section based on their own project/case study, too.

Do you agree this is worth capturing in a little article and do you have a few days to spare over the next months @benmarwick @cboettig @ColinFay @eddelbuettel @MarkEdmondson1234 @mllg @nanxstats @noamross @rcannood @richfitz @zouter ?

_How did you end up in the list above?_

- https://www.r-pkg.org/search.html?q=docker
- https://github.com/search?q=rocker+docker+r

**Comment by eddelbuettel** [comment]
Thumbs up, in principle, though there is a lot to digest.   First differences may be between _building Rocker_ which is narrower and an overview of _various Rocker use cases_ which may be a little disconnected.   But count me in (as saying "sure" is way easier than actually doing work ... ).

But there is potentially a lot here so maybe more than a single paper?   

Also, just to spread it even further:  container "variants" like singularity may a (sub-)topic too.

**Comment by ColinFay** [comment]
Count me in! 

As Dirk said, there might be a lot to cover for just one article. 

Here are some use-cases I can think of from a personal experience/POV 
- Deploying Shiny applications into production
- Deploying RStudio Server in production, for example in a pharmaceutical context where you've got to lock dev and analysis at a moment in time. 
- Using a docker image as a tool for teaching: that's one of the reason behing the [r-db](https://github.com/ColinFay/r-db) image. I tried to put in there a series of databases packages and their sys-req when needed, so that when I need to teach how to use R with a database I "just" have to run this image and I've got everything I need. 
- Using a docker image as a tool for CI/CD, which is the idea behind [r-ci](https://github.com/ColinFay/r-ci), which I use in my GitLab CI workflow for checking packages.
- Also, another toy project, which is powered by NodeJS and rocker containers, that allows to compare code for various versions of R : https://srv.colinfay.me/r-online 
- I'm also working with Carl and Dirk on implementing (older versions of R)[https://github.com/rocker-org/rocker-versioned/issues/138]. This might also be a cool thing to talk about. 

Side comment: I wonder if packages like `{dockerfiler}` or `{stevedore}` are to be put in the same basket as `rocker`, as both can be used to build any dockerfile / manage any docker container. Unless we choose to make an explicit integration of R package used for Docker a part of rocker. 
So this might be two papers here: one about use-cases for rocker and another about the ecosystem of R packages around Docker.

**Comment by cboettig** [comment]
cc @karthik (https://github.com/karthik/holepunch)

:+1: Would be great to gather these in one place.  Since many of us are academics, doing this in paper format is a good way to incentivize things a little; though a more dynamic web format may also be appropriate (though those can get stale easily too).  In any event, a bit of reflection from a broad group about the current state of this ecosystem, what it can already do, what it needs, and where it might be going would definitely be valuable

**Comment by MarkEdmondson1234** [comment]
Same as above, happy to help if I can. My prime use case are Docker images for Cloud services that do not support R as first-class citizen, biased to Google but part of the fun is that most cloud services are moving to containers these days.

**Comment by nanxstats** [comment]
-sounds like a good idea. I'm happy to contribute a section on my package [liftr](https://liftr.me/), which is about rendering R Markdown documents with containers, for achieving OS-level reproducibility.

**Comment by rcannood** [comment]
Great initiative! I (and most likely @zouter as well) would be willing to share our experiences with the following topics:
* [babelwhale](https://cran.r-project.org/web/packages/babelwhale/index.html): Running a Docker from R with Singularity or Docker as back-end. This is really useful in HPC environments where a user might not have root access but is able to install Singularity instead of Docker.
* [dynwrap](https://github.com/dynverse/dynwrap_containers/blob/master/.travis.yml): For this project, we use travis-ci to build rocker-derived containers, test them, and only push them to docker hub (from travis-ci.org) if the integration tests succeed.
* [dynmethods](https://github.com/dynverse/dynmethods): In order to evaluate ±50 computational methods which all used different environments (R, Python, C++, ...), we wrapped each of them in a docker container and can execute these methods from R. Again, all of these containers are being built on travis-ci, and will only be pushed to docker hub if the integration test succeeds.

@nuest Your 'recent tweet' links back to this page.

**Comment by benmarwick** [comment]
Yes, happy to contribute to a journal article that is a rocker use-case survey. I could add a remark about the place of rocker in research compendia

**Comment by noamross** [comment]
Good idea! I could discuss using Rocker in different CI/CD systems, as well as using Rocker to set up a common work environment for teams - I've been working with Carl on porting our custom GPU setup into a standard Rocker template.

**Comment by nuest** [comment]
Wow.

I am extremely glad about the positive feedback by all of you. I'll do my best to make this a pleasant effective collaboration. Some replies to your comments:

- _re. academic paper_: the targeted output is settled then. This document does not use the R Journal template by accident, but feel free to suggest other venues.
- _scope/split up into two articles and content_: I [added](https://github.com/nuest/rockerverse-paper/commit/f62d24d57ea616848183a3b21e728ceb6dfa0c27) all mentioned topics to the paper draft, including your handles if you suggested it. I suggest to see how much we have and how it connects first and then re-visit the scope in a few weeks (see also #4). I deliberately did not use more than one level of structuring for now, and personally I'd be happy with a "collection basket" approach.

**Next steps**

- Write text where your handle appears!
  - Please keep one sentence per line.
  - We are a quite large group now, so a real-time editing environment _might_ work better. I'd like to give GitHub a try though, as I've never written a paper on this platform :-). Please leave your :-1: on this comment if you can _not_ live with that.
- Add bulletpoints to any section or open issues as you see fit, especially discussion/outlook
- I'd like the initial enthusiasm to fuel our activity over the next weeks. If you can _not_ put in a first draft of your content and spend a (cummulative) day on writing until the end of August, please leave a comment so we can adjust the schedule.
- A couple of _telephone conferences_ should help us to consolidate the text and write discussion/outlook sections. This could generate real value, as we might be able to bring in everyone working on/with containers in the R community. On August 14 I will schedule two calls in September to allow as many people to attend as possible: https://doodle.com/poll/2gdenwqaa4cqzwnb

@rcannood: Tweet-Link fixed - thanks!

**Comment by nuest** [comment]
@karthik Would you be interested to write up a little segment about [holepunch](https://github.com/karthik/holepunch) (unless you're pursuing another publication of course) ?

@dtenenba @lshep (sorry to miss you in the first call for participation!) Would you be interested to contribute a short section on the Bioconductor images?

**Comment by dtenenba** [comment]
@nuest Thanks for asking but I haven't been involved in the Bioconductor project for the last few years.

**Comment by lshep** [comment]
@nuest  Let me check with my supervisor. I will get back to you in the next day or two.

**Comment by karthik** [comment]
@nuest Yes absolutely!

**Comment by nuest** [comment]
Hi all,

I've just made you collaborators on the project, so please use branches/forks/pull requests as you see fit, though I'd like to keep an eye on the master branch so that you don't have to worry about merging. Just ping me.

I'll also stop pushing directly to `master` myself :-)

**Comment by lshep** [comment]
I received permission to participate and would very much like to contribute a section about Bioconductor.  My colleague  @nturaga and I have been managing Bioconductor dockers so we would write the section together.

**Comment by nturaga** [comment]
Hi @nuest I'm part of the Bioconductor core team and over the last few months I've been working on making some Bioconductor images, and my colleague @lshep invited me to this page. I'm happy to contribute.

**Comment by nuest** [comment]
@lshep @nturaga Thank you! Please feel free to open a PR or push your changes to a branch, see the proposed next steps here: https://github.com/nuest/rockerverse-paper/issues/3#issuecomment-515748326

**Comment by nuest** [comment]
**All**: Please don't forget to fill out https://doodle.com/poll/2gdenwqaa4cqzwnb so we can have a couple of conversations. (It's holiday season, so no worries if you don't see this. Just want to increase the chances of selecting a sport that works for you.)

Thanks!

**Comment by richfitz** [comment]
I'm happy to contribute something on `stevedore` and can also talk about our experiences using R-based docker images in production environments.  Bits below copied from a chat with @noamross earlier this year

> We use them as key parts of our reproducible research pipeline (we need to write this up still) but see https://github.com/vimc/orderly/blob/master/docker/Dockerfile for the image, here https://github.com/vimc/montagu-machine/blob/master/docs/diagrams/OrderlyWeb%20architecture.png for how we use it and here https://github.com/vimc/montagu-machine/blob/master/docs/diagrams/VIMC%20architecture.png for the context around that
> We also use it in our load-balanced shiny server https://github.com/mrc-ide/twinkle/blob/master/shiny/Dockerfile
> I use it also for testing, for a meta example here in `stevedore` which is an R client for docker : https://github.com/richfitz/stevedore/blob/master/inst/images/tester/Dockerfile

One thing from the above that might be interesting is using docker to containerise R for use as part of a multi-language setting.  So our web developers can use whatever language they want and our analysts can write R however they want and we smooth it all over with docker.  However, we typically do the orchestration of that with python :snake::see_no_evil:

**Comment by nuest** [comment]
**Hi all**! As a friendly reminder to start writing a few paragraphs, I have scheduled two online meetings on September 9. If you have not participated in [the Doodle](https://doodle.com/poll/2gdenwqaa4cqzwnb), then please still do it or let us know if you can make one of the two planned times:

- #7 
- #8

**Comment by ColinFay** [comment]
Should be able to make it for a call, I'll check my calendar and let you know.

**Comment by noamross** [comment]
@nolistic and @jnollis would be excellent to have as co-authors if they are interested in contributing a couple of paragraphs on the use-case of API deployment.

**Comment by noamross** [comment]
@nolistic and @jnolis would be great co-authors to have aboard if they are interested in contributing a couple of paragraphs on the use-case of API deployment.

**Comment by nuest** [comment]
@thebioengineer I saw your package https://github.com/thebioengineer/dockyard - interesting stuff.

Would you be interested to contribute a short section on the package to this collaboratively written article? Especially the relation to other packages such as `containerit`, `dockerfiler` and `stevedore` would be helpful.

**Comment by thebioengineer** [comment]
hey @nuest, this looks like a really interesting project and I would be interested to see how I can help. Admittedly I had not seen the other packages before but I am happy to investigate, and maybe we can all learn from one another to make a really nice API to docker through R.

**Comment by jnolis** [comment]
Hi! Me and @nolistic can contribute on how Rocker is used in production. We'll reference our open-source [R TensorFlow API repo](https://github.com/tmobile/r-tensorflow-api) and talk about the work done at T-Mobile with it.

Thanks @noamross!

**Comment by nuest** [comment]
Thanks to everyone who contributed thus far, recently @ColinFay @eddelbuettel @karthik @noamross :tada:

I've integrated the different contributions into the master branch, with some open discussions about changes that I would suggest as new pull requests, with some relevant pending changes: #25 #28 #30

------

@jnolis and @nolistic That would be a great contribution! I've tentatively added a bullet point with your handles in the "Deployment" section, but you're welcome to put the content into another (new?) section if you think that fits better.

------

@benmarwick Would you be able to provide a short section on research compendia this month? I think you could simply summarise your "... R (and friends)" article, describe how `rrtools` uses containers, and highlight a few existing research compendia. _What do you think?_

------

@MarkEdmondson1234 When would you be able to provide your content about deploying R apps to clouds?

------

@richfitz I added a few words about the packages, including `stevedore` - it would be most helpful if you give that a review. But your story about R in multi-language environments and how you make that happen with containers would be really interesting to hear!

------

I hope the next contributions fall into place better now with some introduction statements in each section. I also tried to start each paragraph with a project/package name and link, to help readers to orient themselves.

Looking forward to see more contributions and discussion!

**Comment by nuest** [comment]
Please find a merged version including the PRs #25 #28 #30 here, if you want to get an overview of the current state https://uni-muenster.sciebo.de/s/fk1jwiVoNBmsnYL

I'll continue to use this issue for reminders, but with the structure taking shape I created issues on the sections that need work: #32 #33 #34 #35 #36 #37 #38 #39 #40 #41

Until the end of the month, I'll mostly take care of my own sections.. Please open issues/PRs or comment here as you see fit, and let's keep an eye on a first milestone: #27

**Comment by MarkEdmondson1234** [comment]
Hello, I broke/dislocated my arm so have got delayed but I’m still following progress and will look to get some drafts ready by end of next week.


________________________________

**Comment by nuest** [comment]
Thanks Mark for the update. I am very sorry to hear about your accident - hope you recover soon!

Looking forward to your draft, I am really interested in your work and experiences and think they can make a great addition to the overall picture.

**Comment by nuest** [comment]
:point_right: https://github.com/nuest/rockerverse-paper/issues/9 :100:

**Comment by Hong-Revo** [comment]
Hey all, I only just found this repo. I have an [AzureContainers](https://github.com/Azure/AzureContainer) package which is for working with containers in Azure. It's also on [CRAN](https://cran.r-project.org/package=AzureContainers).

Among other things, you can spin up a container instance, push images to an Azure container registry, and deploy Kubernetes clusters. It also provides a thin shell on top of the docker, kubectl and helm binaries. I don't know if it's too late to contribute, but if not, I could write something up.

**Comment by nuest** [comment]
@Hong-Revo It's surely not too late! Your use case and package would be a very welcome contribution. I guess the section on deployment - see #36 - fits best?

**Comment by Hong-Revo** [comment]
Great, thanks. What kind of timetable do you have in mind? Is there a deadline for publication?

**Comment by Hong-Revo** [comment]
Also pinging @dselivanov who is writing a very nice [RestRServe](https://github.com/dselivanov/RestRServe) package for serving requests. It's parallelised, unlike plumber which can only handle 1 request at a time. Would be good to see this mentioned as well.

**Comment by nuest** [comment]
@Hong-Revo Re. deadline, see #26 and #27 - it would be great if you could provide a first draft of your contribution by the end of this month.

@dselivanov: Interesting package! Please feel free to open an issue and let us know, what you do with containers or what deployments you use containers for. Would be great to have more lessons learned about practical experiences with apps based on Rocker/Docker containers.

**Comment by nuest** [comment]
Hi all! Please, be so kind to check your calendars if you can make one of the suggested times for a discussion call. I'm happy to lead the write-up of contents and am thankful for the diverse inputs up to now, but it would be great to have a conversation about the big picture to really complete this manuscript :point_right: **https://www.doodle.com/poll/3wt6gm5u555uwfty**

I understand if you're busy: Please leave your comments in the manuscript, or also as a comment in #9 

@eddelbuettel
@ColinFay
@cboettig
@nanxstats
@rcannood
@benmarwick
@noamross
@dtenenba
@lshep
@karthik
@nturaga
@richfitz
@thebioengineer
@jnolis

**Comment by Hong-Revo** [comment]
I'm fairly easy with times for the call.

**Comment by nuest** [comment]
My sincere apologies :pray: _I messed up by failing to announce a date for the call in time._ A bunch of you would have been available this week! I'll try to make up for it with another push on the content during the next days to make the goal of a preprint by the end of the year #27.

I just updated the Doodle with selective times next week, though I think this is a long shot. I'll nevertheless announce a date Sunday evening (my time): :point_right: https://www.doodle.com/poll/3wt6gm5u555uwfty

_If we cannot make the call happen, there's still next year._ The preprint doesn't have to be perfect :wink: but we can use it to elicit feedback from the wider community (there's rstudio::conf in January, see #26).

--------

**I thank all of you for this adventure of "cold calling" people via @-mentions and bringing them together to work on this manuscript. I wish you all a good end of the year :christmas_tree: :snowman_with_snow:  _!_**

**Comment by nuest** [comment]
Hi everyone. Only three people would be available for a call this week, which is very understandable but not helping the intention of having a broader discussion about the conclusions section for the manuscript.

**Updated suggestion for next steps**:

- @nuest wraps up loose ends in the current draft and makes an attempt at adjusting content length of the respective use cases and package descriptions (some need shortening, some might need some more detail or background), reaching out to contributing authors where needed.
- @nuest writes first iteration of conclusions
- @nuest posts draft of "preprint-ready" submission by the end of the year > continues in #27 

@eddelbuettel @ColinFay @cboettig @nanxstats @rcannood @benmarwick @noamross @dtenenba @lshep @karthik @nturaga @richfitz @thebioengineer @jnolis Please chime in any time if you think this is not feasible, or if you'd like to contribute to one of the tasks above during the next days.

**Comment by karthik** [comment]
I am not available for a call till January. Please send out another poll with a longer lead time. Also (I realize this may not be possible) but an email would be helpful as this type of group request is hard to wrangle amidst a very long GitHub issue thread.

**Comment by nuest** [comment]
Hi everyone! The paper content is progressing, naturally at a slower pace than desired. My self-inflicted deadline is too easy to push. Nevertheless, please let me point all of you to two important actions:

- #65 suggests to remove some sections from the manuscript - please comment!
- The conclusions can be much stronger with your ideas and thoughts. Please read and open PRs or issues as you see fit. _Thanks!_

**Comment by nuest** [comment]
Preprint is out: #27

I sent an email with more infos to all of you!

Next steps: #26

**Comment by nuest** [comment]
Preparing for submission now, see #26
