### ISSUE TITLE
Section on non-Debian images

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#33]
IMO worth surveying, would welcome contributions.

@gaborcsardi Hi there! Not sure I've pinged you on this little project before: I'm collecting bits and pieces for a "lay of the land" around R and containers. _Would you be interested to contribute a couple of short sections on usage of containers in R-Hub? To me especially the challenges and lessons in maintaining images for different distributions would be a welcome contribution.

**Comment by nuest** [comment]
I've just found a previous comment with some background reasoning. If Gabor is too busy, someone else can try to present the argument:

https://github.com/r-hub/rhub-linux-builders/issues/43#issuecomment-529834736

**Comment by gaborcsardi** [comment]
Hi Daniel, IDK if I'll have time to write something, to be honest. If you have questions about the R-hub containers, me or @maelle will be happy to answer them.

**Comment by nuest** [comment]
Thanks for getting back to me! No worries, I think I can present the argument myself, and if you have time you can give the section a read - I'll mention it here in the issue.

@maelle Your ideas or feedback are of course very welcome (in this section or others).

**Comment by gaborcsardi** [comment]
@nuest Sounds perfect!
