### ISSUE TITLE
Section on clients

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#34]
Contributions welcome, e.g. from @richfitz or @thebioengineer - but I can also write that.

**Comment by thebioengineer** [comment]
Sorry for the delay. I am happy to take a stab at it. I'll get a branch going soon. @richfitz Any feedback once I commit the branch would be appreciated!

**Comment by richfitz** [comment]
Sure, please ping me (and sorry, I've had very little spare bandwidth in the second half of this year)

**Comment by rcannood** [comment]
I took a look at @thebioengineer's modifications in #51, changed a few things, and merged everything into master. The section needs a bit more work still, though.

Also, in order for the table to render properly, you currently need to install [my fork](https://github.com/rcannood/rticles/) of the rticles package until a PR is merged and published on CRAN.

**Comment by nuest** [comment]
Thanks @rcannood !

@richfitz How's the spare time beginning of this year? Would you be interested to contribute? I think I can write a short section on stevedore myself, so your time might be better spend in the conclusions and in relating the existing packages to each other. Anyway, contributions very welcome!

**Comment by nuest** [comment]
@richfitz Final ping: here is my take on `stevedore`: https://github.com/nuest/rockerverse-paper/commit/89d5069562b16e894190bf7aedfc84a837213aae
Feedback welcome. I'm also sure you might have use cases why you started stevedore, those are still welcome.
