### ISSUE TITLE
Section on capturing environments

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#35]
I'm happy to take the lead on the section, should be pretty straightforward to write.

@nanxstats I think the liftr content is a bit too long, as it partly repeats work already published elsewhere - do you want to give it a go, or may I do an attempt to flesh out the most important bits?

**Comment by nuest** [comment]
@cole-brokamp Hi there! I realise no I have not pinged you yet about this collaboratively writting article surveying the state of the "Rockerverse". Would you be interested in contributing a little section on `rize`, and contribute as you like to other sections, the discussion, etc. ?

**Comment by cole-brokamp** [comment]
Thanks for thinking of me, @nuest, I would be happy to contribute.  A pull request with an added section on `rize` is what you are thinking?

**Comment by nuest** [comment]
Great! A PR based on the `master` branch would be great. There is already a bullet point for `rize`, but I'm open to your suggestions into other sections where it would fit better. Don't forget the author list and the contributions section.

Beyond that, feedback on any section (see respective issues) and especially your general observations or expectations in the discussion section (just bullet points for now) would be highly appreciated!

**Comment by cole-brokamp** [comment]
Hi @nuest, I've decided to archive `rize` and not focus on its development any longer since we are switching to using the `renv` package from R Studio, rather than our own `automagic` package to manage dependencies.  Sorry for the inconvenience, but I think its best to not include a `rize` section for this reason.

**Comment by nuest** [comment]
Thanks for the heads up!

Just out of curiosity: `renv` suffices for your cases - no need for containers? And what about the nice library detection from `automagic`, any plans about that?

**Comment by cole-brokamp** [comment]
`renv` basically replaces automagic completely and then we can run it inside a container.  `renv::snapshot()` is the equivalent to `automagic::make_deps_file()` and then you can just copy the `renv.lockfile` to the container and use `renv::restore()` to install versioned dependencies.  See here for some more details: https://rstudio.github.io/renv/articles/docker.html

I am exploring some more options on possibly transitioning `rize` completely using this package or maybe rewriting our `dep` package (which was originally meant as a successor to automagic) to use this backend instead: https://github.com/cole-brokamp/dep

**Comment by nuest** [comment]
[`dockr`](https://github.com/smaakage85/dockr) by @smaakage85 must be added to this section.

**Comment by eddelbuettel** [comment]
Per CRANberries, `dockr` was thrown off CRAN last night: http://dirk.eddelbuettel.com/cranberries/2020/01/11#dockr-0.8.6.  

CRAN only give the usual terse [Archived on 2020-01-11 as check problems were not corrected in time](https://cloud.r-project.org/web/packages/dockr/index.html).

**Comment by smaakage85** [comment]
Hi. Thanks for info, @eddelbuettel . Right now I am trying to find out, why 'dockr' has been removed from CRAN, I want to fix this asap.

**Comment by nuest** [comment]
Closed by https://github.com/nuest/rockerverse-paper/commit/e56e76729a135e18f9384a06d448a84048002269
