### ISSUE TITLE
Section on deployment and cloud services

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#36]
**Needs work!** I'm happy to do some editing, but sadly I can't tell the interesting stories.

Input needed from various parties, e.g. @rcannood @jnolis @nolistic @MarkEdmondson1234

**Comment by jnolis** [comment]
I took a first swing at covering plumber APIs and the T-Mobile work. I put it in a separate branch. It needs some revision but let me know if that's roughly in line with what you were thinking!

**Comment by nuest** [comment]
Thanks @jnolis :+1: I'll take a look next week.

Until then, @Hong-Revo, please note the branch `deploying-to-production`](https://github.com/nuest/rockerverse-paper/tree/deploying-to-production) if you want to start working on describing the use case and experiences from [your work with Azure](https://github.com/Azure/AzureContainers). I'd be keen to hear about your usage of Rocker images and the lessons you learned in deploying and maintaining Rocker-based infrastructure!

**Comment by Hong-Revo** [comment]
I've added a bit on Kubernetes, along with an example of using AzureContainers to talk to k8s. Hopefully it's not too Microsoft-specific!
