### ISSUE TITLE
Section on CI and CD

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#37]
**Needs work!** I'm happy to do some editing, but sadly I can't tell the interesting stories.

Input needed from various parties, e.g. @MarkEdmondson1234 @rcannood

**Comment by eddelbuettel** [comment]
In a way there is not that much to it: you just place sufficient infrastructure in a container to run `R CMD check` on it.  I switched a few of my repos to it, and started some notes on it that I need to get back to "one day".

**Comment by MarkEdmondson1234** [comment]
I rely on this concept quite a lot, perhaps I can put more detail about it.  I change R code, commit to GitHub and it builds the Docker container with the new changes, which is then called from the running environments such as Kubernetes, Airflow KubernetesPodOperator, Cloud Run or a container running on a VM.

**Comment by nuest** [comment]
@MarkEdmondson1234 I restructured the sections quite a bit, but I think most of your content should still be there :-) Happy to get a review of the sections by you, since I think you actually do a lot more than what is hinted at. Feel free to open a PR or new issues for the final submission.
