### ISSUE TITLE
Section on shared work environments

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#38]
The section already has some good content - possibly needs some shortening and editing, not much else.

----------

@gordonwoodhull @shaneporter @s-u Hi there! I'm putting together a little "lay of the land" of containers in R, find the current draft [here](https://nuest.github.io/rockerverse-paper/master.pdf). _Would you be interested in contributing a paragraph on the `RCloud` container and your experiences with deploying R-based apps etc.?_

----------

@fmichielssen @tverbeke @mnazarov Hi there! I'm putting together a little "lay of the land" of containers in R, find the current draft [here](https://nuest.github.io/rockerverse-paper/master.pdf). _Would you be interested in contributing a paragraph on the ShinyProxy (https://www.shinyproxy.io/), how it uses containers, and your experiences with deploying R-based apps in the cloud etc.?_

- [x] ShinyProxy itself runs in containers (https://www.shinyproxy.io/deployment/) and also spins up containers for sessions (https://www.shinyproxy.io/getting-started/).
  - https://github.com/openanalytics/shinyproxy
  - https://github.com/openanalytics/containerproxy and https://www.containerproxy.io/
  - own base image?? see https://github.com/openanalytics/r-base

**Comment by nuest** [comment]
- [ ] briefly describe that `Binder` is _not_ using Rocker base images for _reasons..._

**Comment by nuest** [comment]
@betatim @choldgraf collaborative writing project here - would you be interesting in contributing a bit more about the Binder use case for Docker + R? So far @karthik wrote about wholepunch.

**Comment by choldgraf** [comment]
Thanks for reaching out! It'd be helpful if you gave a more specific prompt for what you need - how much text, what questions you'd like answered, etc...

**Comment by nuest** [comment]
@choldgraf Right, that was rather unspecific. If you have 15 minutes to spare, you could take a look at the abstract and the "Jupyter Docker Stacks" paragraph in the section "Data Science Images". There might be more to tell about how this stack specifically handles R. _Also, Is there a citation commonly used for Conda?_

If you have a bit more time, you could write 8-10 sentences about the how repo2docker supports R (what config files, how different R versions are handled now). This might more be down @betatim's alley, and I could probably also do that myself, but there are plenty of section I can spend time on instead :-).

What do you think, you wanna join?

**Comment by choldgraf** [comment]
hey @nuest - sorry for the slow response here, I am slammed preparing for a trip to Australia to kick off a project. If I can help out briefly let me know where my time would be best-spent, but apologies if you've already got this resolved

**Comment by nuest** [comment]
@choldgraf Nothing concrete here to do, I think we've got Binder vs. repo2docker vs. holepunch vs. Whole Tale covered quite well. Thanks! And have a good trip!
