### ISSUE TITLE
Section on research compendia

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#40]
It would be great @benmarwick can contribute his experiences and insight here. Plan B would be me writing this section..

**Comment by benmarwick** [comment]
Thank you, I've started drafting here: https://hackmd.io/@Sq-NZxXnQQGtVzoZDwyznA/Sk0ijR8IV Could I ask you to talk a look and let me know if that seems suitable?

**Comment by nuest** [comment]
Sorry @benmarwick for not getting to this sooner - I even have to admit your draft slipped by.

So today I've learned a bit about the difference between author and committer, and added your draft "for you" (more transparent would have been if I'm the author and you the committer, but I really wanted to try out everything), then made a few changes. Your review is very welcome, see 

https://github.com/nuest/rockerverse-paper/pull/56

--------

Notes to self:
<details>

<code>
daniel@nuest rockerverse-paper [compendia]$ git show 4c1871e7f34b6a4c842ed3d7df015bf5fd8e3a64
commit 4c1871e7f34b6a4c842ed3d7df015bf5fd8e3a64
Author: Ben Marwick <benmarwick@hotmail.com>
</code>

Then added the HackMD and followed https://stackoverflow.com/a/30335845/261210

<code>
GIT_COMMITTER_NAME="Ben Marwick" GIT_COMMITTER_EMAIL="benmarwick@hotmail.com" git commit -m "Add draft based on https://hackmd.io/@Sq-NZxXnQQGtVzoZDwyznA/Sk0ijR8IV" --author="Ben Marwick <benmarwick@hotmail.com>"
</code>

Seems to work:

![image](https://user-images.githubusercontent.com/1325054/72506197-b9d51280-3841-11ea-803a-b00ccba6e35f.png)

https://github.com/nuest/rockerverse-paper/commit/ec050cf999c4ece755fc1f5a236c33e6cff48b9e

</details>

**Comment by nuest** [comment]
@benmarwick Feel free to open a PR or re-open this if you see potential for improvement.
