### ISSUE TITLE
WholeTale

### ISSUE THREAD

**Issue by cboettig** [nuest/rockerverse-paper#43]
@nuest Really nice collection here.  Can't recall if we've discussed it in other channels, but another project I think we may want to list / enlist is the work at https://wholetale.org, a reproducible research environment that I believe extends on rocker images for it's R images.  @craig-willis would probably be a good point of contact?

**Comment by nuest** [comment]
Right! :+1: I agree WholeTale is worth mentioning, as it is a great example of the big things you can build upon Rocker. Our own project o2r operates on a smaller scale, but could also be added.

I think these also present a good counterpoint to Binder, which - for good reasons - uses it's own images and not the Rocker stack.

@craig-willis It would be great if someone from your team would be willing to contribute a short section on the reasoning why you use Rocker images and the experiences you made. Of course your input for the general discussion would also be very valuable.

**Comment by craig-willis** [comment]
Thanks @cboettig and @nuest.  I wasn't aware of this paper and would be happy to contribute.

**Comment by nuest** [comment]
@craig-willis Would you still be interested in contributing a paragraph?
