### ISSUE TITLE
RStudio images and professional products

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#46]
**RStudio has some Docker images on Docker Hub: https://hub.docker.com/u/rstudio**. Not all of them have open Dockerfiles, but some stuff is on GitHub:

- https://github.com/rstudio/docker-r-session-complete
- https://github.com/rstudio/r-docker

As per https://support.rstudio.com/hc/en-us/articles/360021594513-Running-RStudio-with-Docker-containers it is

> _increasingly common to run RStudio professional products in Docker containers, especially in cloud environments. Below are are a few recommendations for running RStudio with containers._

There are also some further infos and docs:

- https://support.rstudio.com/hc/en-us/articles/360019253393-Using-Docker-images-with-RStudio-Server-Pro-Launcher-and-Kubernetes
- https://docs.rstudio.com/connect/1.7.2/admin/server-management.html#server-docker
- https://rstudio.com/wp-content/uploads/2018/03/RStudio_Docker_3-9-2018.pdf
- (in Nov 2017 running RStudio Connect in a container was not recommended - what changed?) https://community.rstudio.com/t/running-rstudio-connect-through-a-docker-container/3053

_Hi @koverholt @slopp @glin !_ Sorry for the cold @-mention. I'm coordinating a ~~little~~ collaborative research paper about "everything containers and R" - see the current draft at https://nuest.github.io/rockerverse-paper/master.pdf. I came across RStudio's collection of Dockerfiles and images and wonder if you'd be interested and able to contribute a short section on the usage of containers by RStudio and its customers and your experiences and reasoning. I think that would be a very interesting read, first of all, and also could provide a helpful resource if contrasted with the other presented projects (which large build on Rocker images). _Looking forward to hear from you!_

**Comment by nuest** [comment]
One more try pinging @koverholt @slopp @glin - it would be great to include a quick recap of your experiences and insights in this work.

**Comment by nuest** [comment]
@slopp Thanks for your contributions in #53

I changed the language to better fit who "we" is, as this is not an RStudio communication, see https://github.com/nuest/rockerverse-paper/commit/7294efd33048d2b55574bc1b6f662f1222c27650

_Are you OK with those changes?_

It would be great if you could have a link/reference for the Singularity aspect and can clarify (here) one thing for me: RStudio Connect is _not_ running in containers or using containers?

------

FYI: I'll reach out to you and other coauthors with the final draft hopefully by the end of the week. Thanks!

**Comment by slopp** [comment]
@nuest  I left some comments on your re-wording, please update these changes.

RStudio Connect can run inside of a container, one of the links in the section is to a repository with Dockerfiles for running each of our products inside of a Docker container.

We do not have a reference for singularity, but you can generically reference their support for containers if you'd like.

**Comment by nuest** [comment]
Thanks for taking another look! Should all be fixed in commit linked above.
