### ISSUE TITLE
Add section on outsider

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#54]
I can't believe I forgot to include the outsider package by @DomBennett until now.

@DomBennett: this is the draft for a manuscript about "all stuff with Docker and R". I plan to add a short section in the "Research Compendia" section, as I think that fits your use case best. _Do you agree?_

It would be great if you could give it a quick read: https://github.com/nuest/rockerverse-paper/commit/71205502f9f266e6883e5f2db564b23d3252bb47

Contributions to the manuscript (about outsider or other use cases you have!) are very welcome, just note #27. I hope the package get's through JOSS review soon, I'd love to include a proper reference.

**Comment by DomBennett** [comment]
Thanks @nuest !

I've created a pull-request: https://github.com/nuest/rockerverse-paper/pull/55

Do you think it would be helpful to add a use case like one of the ones you cited in the comment? (https://github.com/DomBennett/om..astral/blob/master/examples/astral.R,
https://github.com/DomBennett/om..raxml#partitioned-dna-analysis)

I worry of taking up too much text.

**Comment by nuest** [comment]
I think the level of detail is good now, the concrete code examples from other cases are likely to be removed to not go into too much detail.
