### ISSUE TITLE
Update Bioconductor section

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#57]
It seems the _Bioconductor_ images described in the article have been deprecated by now, see https://github.com/Bioconductor/bioconductor_docker#deprecation-notice and https://bioconductor.org/help/docker/

I think the new model with community maintained use case images is interesting.

@lshep @nturaga Can you please update the section? This is a bit of unfortunate timing, but should be quick to resolve. Thanks!

**Comment by lshep** [comment]
Yes we will relook at our section and make some updates

**Comment by nuest** [comment]
@lshep Any e.t.a. on the update? Just want to align schedules/tasks.

**Comment by lshep** [comment]
Nitesh and I will look at it tomorrow.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nuest** [comment]
Thanks @nturaga I made some changes to the text, see commit linked above. Please review.

I think you missed some small bits still referring to the now deprecated set-up. Also, the "reduction in layers and image size" also referred to the old image stack AFAICT.

Feel free to re-open this issue or start a PR if my changes introduced incorrect content!
