### ISSUE TITLE
On Singularity

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#6]
There is a bunch of Singularity images found when searching for "rstudio": https://singularity-hub.org/search

Ideally we would review those, or someone starts a Rocker-like consolidation?

![image](https://user-images.githubusercontent.com/1325054/63101185-ce526d80-bf78-11e9-8f31-372c5dd71eb7.png)

**Comment by vsoch** [comment]
Re-sharing some comments from the linked issue!

For Singularity Hub (I can answer this with confidence because I run it) the images there are primarily done by individuals that want to run a container-based analysis on HPC, so that's why you don't see any sort of library of R base images, but you see a lot of images that might include R or other derivatives. There are a few options! If you are incentivized, you could create a collection of images here. You could also try engaging with the Sylabs folks, their [cloud](https://cloud.sylabs.io/library) does provide several base images. The danger in dumping Rocker images into Singularity (noted in the linked issue) is that the start sequence can [hugely mess up a local machine](https://github.com/sylabs/singularity/issues/3777) because there is less isolation, and the solution is to [do away with the complicated startup](https://github.com/singularityhub/singularity-compose-examples/blob/master/rstudio-simple/rstudio/Singularity) and just start the server. This is more likely an issue for Rstudio and other server based images (and I wouldn't think R?) but I haven't looked at the entrypoint for those containers, so I don't have complete certainty.

Good advice is just to *always* check the entrypoint before running a rocker docker converted to Singularity image.

**Comment by nuest** [comment]
https://cloud.sylabs.io/library/search;query=rstats

**Comment by vsoch** [comment]
I don't see any results (should I / need I be logged in?) but there is an rstudio container, https://cloud.sylabs.io/library/_container/5d22b29d3a2c26622b0382db#container-top

**Comment by vsoch** [comment]
Looks like it installs R from scratch to an ubuntu base:
<details>

```
#------------------------------------------
# nickjer/singularity-r
#------------------------------------------

BootStrap: docker
From: ubuntu:18.04

%labels
  Maintainer Josh Granek
  R_Version 3.6.0
  RStudio_Version 1.2.1335

%help
  This will run RStudio Server with tidyverse and support for knitting

%apprun R
  exec R "${@}"

%apprun Rscript
  exec Rscript "${@}"

%apprun rserver
  exec rserver "${@}"

%runscript
  exec rserver "${@}"


%environment
  export PATH=/usr/lib/rstudio-server/bin:${PATH}

%setup
  install -Dv \
    rstudio_auth.sh \
    ${SINGULARITY_ROOTFS}/usr/lib/rstudio-server/bin/rstudio_auth
  install -Dv \
    ldap_auth.py \
    ${SINGULARITY_ROOTFS}/usr/lib/rstudio-server/bin/ldap_auth


%post
  # Software versions
  export R_VERSION=3.6.0
  export DEBIAN_FRONTEND=noninteractive

  # Get dependencies
  apt-get update
  apt-get install -y --no-install-recommends \
    apt-utils \
    gnupg \
    locales

  # Configure default locale
  echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
  locale-gen en_US.utf8
  /usr/sbin/update-locale LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8

  # Install R
  echo "deb http://cran.r-project.org/bin/linux/ubuntu bionic-cran35/" > /etc/apt/sources.list.d/r.list
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  apt-get update
  apt-get install -y --no-install-recommends \
    r-base=${R_VERSION}* \
    r-base-core=${R_VERSION}* \
    r-base-dev=${R_VERSION}* \
    r-recommended=${R_VERSION}* \
    r-base-html=${R_VERSION}* \
    r-doc-html=${R_VERSION}* \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libcairo2-dev \
    libxt-dev \

  # Add a default CRAN mirror
  echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/lib/R/etc/Rprofile.site

  # Add a directory for host R libraries
  mkdir -p /library
  echo "R_LIBS_SITE=/library:\${R_LIBS_SITE}" >> /usr/lib/R/etc/Renviron.site

  # Clean up
  # rm -rf /var/lib/apt/lists/*

#------------------------------------------
# nickjer/singularity-r
#------------------------------------------
#post
  # Software versions
  export RSTUDIO_VERSION=1.2.1335

  # Install RStudio Server
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    wget \
    gdebi-core \
    libssl1.0.0 \
    libssl-dev
    
  wget \
    --no-verbose \
    -O rstudio-server.deb \
    "https://download2.rstudio.org/server/trusty/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb"
  gdebi -n rstudio-server.deb
  rm -f rstudio-server.deb

  # Add support for LDAP authentication
  wget \
    --no-verbose \
    -O get-pip.py \
    "https://bootstrap.pypa.io/get-pip.py"
  python3 get-pip.py
  rm -f get-pip.py
  pip3 install ldap3

  # Install tidyverse and packages necessary for knitting to HTML 
   Rscript -e "install.packages(pkgs = c('tidyverse','caTools','rprojroot'), \
     repos='https://cran.revolutionanalytics.com/', \
     dependencies=TRUE, \
     clean = TRUE)"

  # Clean up
  rm -rf /var/lib/apt/lists/*

```

</details>

**Comment by eddelbuettel** [comment]
So that looks like a copy what we do -- install prebuild .deb packages for R plus extra this and that.

**Comment by vsoch** [comment]
Yeah, there are definitely many ways to skin this cat! I think @nuest was generally suggesting there might be (akin to how rocker images are provided) a Singularity equivalent. Normally with Singularity you can pull from docker, but the /init sequence doesn't work for Singularity for this particular case.

**Comment by eddelbuettel** [comment]
@vsoch Also please don't conflate the rstudio-containing Docker containers (running a service / daemon) which all other ones. We have many (maybe too many) and very few have an init script. I focus more on plain containers with build customization built on top of rocker/r-base etc for testing etc pp and those should be just fine.

**Comment by vsoch** [comment]
I don’t mean to! A rocker container with that init script (or any for that matter) is what I am referring to as it is a risk to run on a host with Singularity.

**Comment by nuest** [comment]
So we have two kind of use cases for Singularity: the one where the main process is R (like `r-base`) that could just be pulled from Docker ("plain containers" as @eddelbuettel put it), and the ones where there is an init script (like anything with RStudio in it) where simply pulling from Docker does _not_ work and @vsoch has pasted a working `Singularity`-file above.

_Correct?_

**Comment by vsoch** [comment]
Yes, definitely. Anything that just uses R (without the init) is okay, and in fact I'd recommend pulling Docker containers as it kills two birds with one stone. Anything with an init script... run at your own risk! :)

**Comment by nuest** [comment]
@vsoch I've added a first coarse section on Singulartiy - would appreciate your feedback (or even a PR?): https://github.com/nuest/rockerverse-paper/blob/master/manuscript.Rmd#L394

**Comment by vsoch** [comment]
This is another paper?

**Comment by vsoch** [comment]
Seems brief and correct.

**Comment by nuest** [comment]
Yes, another paper :-)... focussed on R, more a lay of the land what exists around containers and Rocker.

Thanks for taking a look!





-- 
Daniel Nüst
Institute for Geoinformatics (ifgi) | University of Münster
Heisenbergstraße 2, 48149 Münster, Germany | +49 251 83 31962
https://nuest.staff.ifgi.de | https://o2r.info

**Comment by nuest** [comment]
Yes, another paper :-)... focussed on R, more a lay of the land what exists around containers and Rocker.

Thanks for taking a look!
