### ISSUE TITLE
Use-case: GUI interfaces to Dockerized research / publication environments

### ISSUE THREAD

**Issue by davclark** [nuest/rockerverse-paper#61]
Over email with @nuest we discussed some of the reasons Gigantum has it's own set of Docker base images. We got into a bigger discussion than what we already included in the paper and agreed to create an issue for a potential inclusion after the initial pre-print.

It's important to acknowledge that there are currently a number of efforts to provide GUIs for researchers and readers to launch one or more Docker containers to enable live interaction with research code and data that's "identical" to what the initial researcher / publisher had set up. These efforts come from commercial and academic players and vary in their degree of openness. So, there is a danger that this discussion could baloon beyond what would fit in the scope of the paper.

For me, these are interesting points that are somewhat generic to any specific platform. They can serve as an outline for what goes into this paper, or perhaps they'll find another home!

- Interaction between Git merges and Dockerized environments, and ways to make this easier (e.g., Gigantum uses individual files and other storage formats that are designed with Git in mind - merges of Dockerfiles on the other hand can easily include multiple installs that will conflict with each other.
- What constitutes a complete record? Different solutions take very different approaches here.
- How to avoid lock-in to a specific platform, issues that create soft lock in
- What is the target audience (especially in terms of required skillset)? Is there a structural separation between "producers" of research projects and "consumers"? Can this be avoided or minimized?

Happy to have conversation about any of that. I've got some fairly sprawling conversation in email with @nuest that I'm happy to copy-paste here (assuming he agrees also).

**Comment by davclark** [comment]
Following up after reading the updated #26, my hunch is that this is a big chunk to add to an already long article. So, while I'm happy to proceed if there's enthusiasm to do so, I'm also happy to kick this to another pub / post somewhere. Personally, peer reviewed articles aren't that important for me... just getting information out! But I think there's enough to cover with this article that it could warrant another peer-reviewed ref.

**Comment by nuest** [comment]
@davclark Maybe you're right and this is rather a separate story. The Gigantum stack is described quite well, I think, in the article: https://github.com/nuest/rockerverse-paper/blob/master/manuscript.Rmd#L389 The graphical client is mentioned as an important feature, but not in detail.

Maybe we continue this in another context? Happy to schedule a call some time in March to chat and develop these ideas further.

Maybe my colleague @MarkusKonk who is the expert on GUI in @o2r-project would like to join?

**Comment by davclark** [comment]
@nuest sounds like we're on the same page - I'd be very happy to do something collaborative like that. While of course I want to promote Gigantum, even more I want to keep the conversation going about improving the quality and accessibility of science. It'd be great to do that with @MarkusKonk, you, and whoever else is interested.

I'm generally busy but flexible in my scheduling (a lot of my work these days is actually programming). Do you want to propose a couple times in March?

**Comment by nuest** [comment]
I'll chat with @markuskonk in the coming days and we'll reach out to you. Closing this until then to proceed with the Rockerverse paper.
