### ISSUE TITLE
Paper focus and potential split up

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#65]
[ This issue is related to #26 and #27 ]

As pointed out in the "Concerns" in #26, the paper reached a considerable length (in pages) and breadth in content by now. _That is really great!_ But based on some conversations with contributors, I'd like to gather some feedback here about the following suggestion:

A "natural cut" within the manuscripts contents are the two parts of "Images" and "Use cases and applications". The former is mostly written by @nuest, and can be can be further divided into "images with R" and "images for use cases and packages". The latter are the sections about Bioconductor, Historic R versions, and Data Science.

**Idea**:  _This article focuses on the use cases and applications part._ The "Container images" content (even if only ~ two pages) goes into a separate paper about comparing R implementations using Docker. I plan to prepare an article about the mentioned `altRnative` package anyway, and we can elaborate on the images for different OS and R interpreters, and how R scripts behave in them in more detail and more in a more understandable/helpful way. I'd move the content to a different repo. Contributors from this group would be very welcome, of course!

Concrete changes:

1. Section "Images for (historic) R versions" would be moved and partly removed
  - @ColinFay's contributions about `r-online` would be moved into the "Capture and create environments" section (or "Development and debugging" - what do you think @ColinFay?).
  - The description of the semantic versioning for Rocker images would be removed, for now, [because I'm not sure they are fully functional at the moment](https://github.com/rocker-org/rocker-versioned/issues/42#issuecomment-550266782)
2. Section "Bioconductor" and "Data Science images" would be integrated into one use case "Image stacks for communities of practice"
3. Sections to revise
  - Abstract
  - Conclusions

Tagging @ColinFay @lshep @nturaga because your contributions are most affected by this.

**Comment by lshep** [comment]
It is great to see all the enthusiasm -  One paper, two paper - no strong opinion - just would be nice to see a paper come to flourish that we can be a part of.

**Comment by benmarwick** [comment]
I'm in favour of the split. The [instructions to authors](https://journal.r-project.org/share/author-guide.pdf) give some good reasons for a paper that is 8-10 pages. Currently we are at [17 pages](https://nuest.github.io/rockerverse-paper/master.pdf). The division of content proposed by @nuest would help to get closer to that target range, and and seems quite coherent.

**Comment by noamross** [comment]
I concur, this seems like a natural split and I think the narrower topic will make for more coherent paper.

**Comment by ColinFay** [comment]
I think capture and create environment might be the best section for r-online

**Comment by nuest** [comment]
https://github.com/nuest/altRnative-paper
