### ISSUE TITLE
Group telco #1

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#7]
We will have a first group call on **Monday, Sep 9 12:00 hrs CEST**, which is 10:00 UTC: https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=9&day=9&hour=10&min=0&sec=0&p1=37&p2=179&p3=137

**Agenda**

- Roll call/introductions
- Contributions so far
- Structure > https://github.com/nuest/rockerverse-paper/issues/4
- Next steps

@nanxstats @benmarwick @ColinFay @noamross @nturaga @richfitz we probably missed your participation in the Doodle because you're on vacation, but it would be great if you could still join one of the two online meetings.

------

You are invited to a DFNconf Meeting:	
-------------------------------------		

Meeting Room Name:   rockerverse paper		
Meeting Room Number: 97976824

In order to join the meeting you can select one of the alternatives:

1. With your Browser under Windows, MacOS, GNU/Linux:
   https://conf.dfn.de/webapp/conference/97976824

2. With a SIP/H.323 room system or SIP/H.323 software client:

   H.323: 004910097976824
   SIP:   97976824@conf.dfn.de
   
3. With a telephone (audio only): 
   Call 0049 30 200 97976824

4. Via Skype for Business:
   97976824@vc.dfn.de

5. Using a mobile smart phone.
   You have to install the Pexip App beforehand:

     Android: https://play.google.com/store/apps/details?id=com.pexip.infinityconnect
     iOS:     https://itunes.apple.com/us/app/pexip-infinity-connect/id1195088102

   Please Enter:

   97976824@conf.dfn.de

Please wait for your host to join the meeting room.

For a connection test look at following website: https://www.conf.dfn.de/beschreibung-des-dienstes/zugangswege/testcall-service/

See our Privacy Policy to learn about your personal data and all your
related rights and obligations: https://www.conf.dfn.de/datenschutz

**Comment by ColinFay** [comment]
Count me in for this one.

**Comment by nturaga** [comment]
@nuest I can make this call.

**Comment by ColinFay** [comment]
Ok I'll be on train, so switching to telco number two #8 :)

**Comment by nuest** [comment]
Call will start in a minute - need to dig out the password!

**Comment by nuest** [comment]
**Participants**

- @lshep 
- @nuest 
- @nturaga 

Discussion

- good job by team Bioconductor :100: 
- there _is_ a need for a short generic intro
- _timeline? venue?_
  - full complete draft by end of October (preprint, see #12), submit before the end of the year
  - have drafts of all sections by end of Sep
  - use October for Discussion/Outlook (collaborative)
  - R Journal, but open for other venues (special issues)
- other deadlines to keep in mind: useR2020 workshops submission?, rstudio::conf (January, for advertising)
