### ISSUE TITLE
Preprint feedback

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#70]
The preprint is published at [arXiv:2001.10641](https://arxiv.org/abs/2001.10641)

**Please leave your feedback here.** Thanks!

**Comment by nuest** [comment]
@gaborcsardi You've been working a lot with containers, so if you'd take a look and let us know what's missing or not well presented, that would be great!

**Comment by gaborcsardi** [comment]
@nuest Most of this is actually new to me, I never researched how containers are used in the R community.... sry.

**Comment by nuest** [comment]
@gaborcsardi Thanks for taking a look. Do you think your personal usage and experiences with containers are adequately captured (R-Hub stuff etc.) ?

**Comment by nuest** [comment]
Ben caught a formatting error in the headline of the section "Using R to power enterprise software in production environments"

https://github.com/nuest/rockerverse-paper/commit/589d242a2af76555c9b05e9fbdd6b5999a8c8ca9

@benmarwick Good catch! I'll wait till you're done with your course preparations and then update the preprint so your participants get a nice version - sounds good?

**Comment by gaborcsardi** [comment]
@nuest yes, very much so, thanks for that!

**Comment by Hong-Revo** [comment]
@nuest Thanks very much for getting this into shape and putting it on ArXiv. I've asked my colleagues to have a look as well.

**Comment by nuest** [comment]
@Hong-Revo Any feedback from your colleagues that we should take into consideration?

**Comment by nuest** [comment]
FYI: new version of the preprint is submitted to arXiv, the differences are https://github.com/nuest/rockerverse-paper/compare/preprint.v1...preprint.v2

**Comment by nuest** [comment]
New version of the preprint is now online: **https://arxiv.org/abs/2001.10641** (versioned: https://arxiv.org/abs/2001.10641v2)

Version 1: https://arxiv.org/abs/2001.10641v1

**Comment by nuest** [comment]
New version of preprint submitted... will update here when online.

Diff: https://github.com/nuest/rockerverse-paper/compare/preprint.v2...preprint.v3
