### ISSUE TITLE
Group telco #2

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#8]
**Monday, Sep 9 20:00 hrs CEST**, which is 18:00 UTC: https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=9&day=9&hour=18&min=0&sec=0&p1=37&p2=179&p3=137

**Agenda**

- Roll call/introductions
- Contributions so far
- Notes from first telco > #7
- Structure > https://github.com/nuest/rockerverse-paper/issues/4
- Next steps

@nanxstats @benmarwick @ColinFay @noamross @nturaga @richfitz we probably missed your participation in the Doodle because you're on vacation, but it would be great if you could still join one of the two online meetings.

------

You are invited to a DFNconf Meeting:	
-------------------------------------		

Meeting Room Name:   rockerverse paper		
Meeting Room Number: 97976824

In order to join the meeting you can select one of the alternatives:

1. With your Browser under Windows, MacOS, GNU/Linux:
   https://conf.dfn.de/webapp/conference/97976824

2. With a SIP/H.323 room system or SIP/H.323 software client:

   H.323: 004910097976824
   SIP:   97976824@conf.dfn.de
   
3. With a telephone (audio only): 
   Call 0049 30 200 97976824

4. Via Skype for Business:
   97976824@vc.dfn.de

5. Using a mobile smart phone.
   You have to install the Pexip App beforehand:

     Android: https://play.google.com/store/apps/details?id=com.pexip.infinityconnect
     iOS:     https://itunes.apple.com/us/app/pexip-infinity-connect/id1195088102

   Please Enter:

   97976824@conf.dfn.de

Please wait for your host to join the meeting room.

For a connection test look at following website: https://www.conf.dfn.de/beschreibung-des-dienstes/zugangswege/testcall-service/

See our Privacy Policy to learn about your personal data and all your
related rights and obligations: https://www.conf.dfn.de/datenschutz

**Comment by nuest** [comment]
**Notes from the first call**

https://github.com/nuest/rockerverse-paper/issues/7#issuecomment-529411417

**Comment by eddelbuettel** [comment]
I had hoped to make the 1st call at 5:00am my time but stayed up too late.  The second is in the middle of my workday so I am unlikely to make that.  Sorry :-/

**Comment by nuest** [comment]
@eddelbuettel No worries - if you can squeeze in a brief look on the [suggested timeline](https://github.com/nuest/rockerverse-paper/issues/7#issuecomment-529411417) and think about (new?!) sections, that you would like to contribute (to), ideally some time this week, that would be great!

**Comment by nuest** [comment]
Participants: @nuest @nanxstats @ColinFay @noamross

**Notes**

- See [notes from the first call](https://github.com/nuest/rockerverse-paper/issues/7#issuecomment-529411417)
- **structure**
  - avoid just having a list of packages
  - categories in R package section
    - clients
    - "wrapping" packages
    - packages "further away" from the Docker API probably fit better the use cases
- _at what level do we want to write this?_
  - specific examples? > to many things
  - more high level, not concrete code, briefly introduce packages
  - provide guidance to readers
  - _what_ can be quickly summarized for many packages, but _focus on the differences_
  - _why_ is more important, but too much for each package... write the "common Why" (overall solved problems)
  - big picture: reproducibility and portability
- **deadlines**
  - Okt. 7 _all contents_ are there
- **process**
  - avoid having to many writing styles mixed
  - try common structure (direction)

**Comment by noamross** [comment]
In this call we discussed, a suggested section structure, so as to homogenize style and make it easer for the main re-writers to make everything flow:

#### Use case (e.g., deployment of images to cloud infrastructure)

-  General description of application (moving images to cloud services to provision them for remote execution, scaling, etc.)
- Key considerations for this case (differences in cloud service APIs, moving built images vs. building remotely, etc.)
- Use case / package / image 1, particularities and design approaches
- Use case / package / image 2, ...
- Use case / package / image 3, ...
- Other things to reference.

**Comment by nuest** [comment]
Just assigning this to me to make sure I'll soon re-read the introduction and the opening statements of each section to match the overall structure suggested here.
